# Generated by Django 2.0.1 on 2018-02-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvw_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('scbz', models.BooleanField(default=False)),
            ],
        ),
    ]
